### ISSUE TITLE
The url of the tool cannot be used.

### ISSUE THREAD

**Issue by Annlean** [muldon/crokage-emse-replication-package#1]
Hi, I found your tool from a paper. It's a very great tool! But, when I wanted to use the tool, I found the URL you provided ("http://isel.ufu.br:9000/ ") cannot be opened, can you provide  another method to use the tool or a new url? Thank you!

**Comment by muldon** [comment]
Sorry Annlean, we had some issues but the server is back online again. Please try now.

**Comment by muldon** [comment]
Sorry Annlean, we had some issues but the server is back online again.
Please try now.
